---
- name: Install MySQL server
  sudo: yes
  apt:  pkg=mysql-server state=latest

- name: Allow access to MySQL from anywhere
  sudo: yes
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" "line=#bind-address = 0.0.0.0"
  notify: restart mysql

- name: Add root user from anywhere to MySQL
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;"

# - name: Create optimcore MySQL user
#   command: mysql -u root -e "CREATE USER 'optimcore'@'%' IDENTIFIED BY 'optimcore'; FLUSH PRIVILEGES;"

- name: Create and add optimcore user from anywhere to MySQL
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'optimcore'@'%' IDENTIFIED BY 'optimcore'; FLUSH PRIVILEGES;"

- name: Create MySQL database optimcore
  command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS optimcore;"
