---
- name: Drop database
  command: /usr/bin/php app/console doctrine:database:drop --force --no-interaction chdir={{ project_root }}
  ignore_errors: yes

- name: Create database
  command: /usr/bin/php app/console doctrine:database:create --no-interaction chdir={{ project_root }}

- name: Create schema
  command: /usr/bin/php app/console doctrine:schema:update --force --no-interaction chdir={{ project_root }}

# - name: Migrate database
#   command: /usr/bin/php app/console doctrine:migration:migrate --no-interaction chdir={{ project_root }}

# - name: Load fixtures
#   command: /usr/bin/php app/console doctrine:fixtures:load --no-interaction chdir={{ project_root }}