---
- name:     Install Composer
  shell:    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

- name:     Update composer packages
  command: /usr/bin/php composer.phar update chdir={{ project_root }}